export const COMMON_TERMS: Record<string, string> = {
  // Siglas de Centros de Geoinformação
  '1cgeo': '1° Centro de Geoinformação',
  '2cgeo': '2° Centro de Geoinformação',
  '3cgeo': '3° Centro de Geoinformação',
  '4cgeo': '4° Centro de Geoinformação',
  '5cgeo': '5° Centro de Geoinformação',
  '1 cgeo': '1° Centro de Geoinformação',
  '2 cgeo': '2° Centro de Geoinformação',
  '3 cgeo': '3° Centro de Geoinformação',
  '4 cgeo': '4° Centro de Geoinformação',
  '5 cgeo': '5° Centro de Geoinformação',
  '1ºcgeo': '1° Centro de Geoinformação',
  '2ºcgeo': '2° Centro de Geoinformação',
  '3ºcgeo': '3° Centro de Geoinformação',
  '4ºcgeo': '4° Centro de Geoinformação',
  '5ºcgeo': '5° Centro de Geoinformação',
  '1º cgeo': '1° Centro de Geoinformação',
  '2º cgeo': '2° Centro de Geoinformação',
  '3º cgeo': '3° Centro de Geoinformação',
  '4º cgeo': '4° Centro de Geoinformação',
  '5º cgeo': '5° Centro de Geoinformação',
  '1°cgeo': '1° Centro de Geoinformação',
  '2°cgeo': '2° Centro de Geoinformação',
  '3°cgeo': '3° Centro de Geoinformação',
  '4°cgeo': '4° Centro de Geoinformação',
  '5°cgeo': '5° Centro de Geoinformação',
  '1° cgeo': '1° Centro de Geoinformação',
  '2° cgeo': '2° Centro de Geoinformação',
  '3° cgeo': '3° Centro de Geoinformação',
  '4° cgeo': '4° Centro de Geoinformação',
  '5° cgeo': '5° Centro de Geoinformação',
  '1ocgeo': '1° Centro de Geoinformação',
  '2ocgeo': '2° Centro de Geoinformação',
  '3ocgeo': '3° Centro de Geoinformação',
  '4ocgeo': '4° Centro de Geoinformação',
  '5ocgeo': '5° Centro de Geoinformação',
  '1o cgeo': '1° Centro de Geoinformação',
  '2o cgeo': '2° Centro de Geoinformação',
  '3o cgeo': '3° Centro de Geoinformação',
  '4o cgeo': '4° Centro de Geoinformação',
  '5o cgeo': '5° Centro de Geoinformação',

  // Abreviações de escalas
  '25k': '1:25.000',
  '50k': '1:50.000',
  '100k': '1:100.000',
  '250k': '1:250.000',
  '25.000': '1:25.000',
  '50.000': '1:50.000',
  '100.000': '1:100.000',
  '250.000': '1:250.000',
  '25000': '1:25.000',
  '50000': '1:50.000',
  '100000': '1:100.000',
  '250000': '1:250.000',

  // Abreviações de tipos de produto
  'carta topo': 'Carta Topográfica',
  'carta orto': 'Carta Ortoimagem',
  'carta ortoimg': 'Carta Ortoimagem',
  'cartas topo': 'Cartas Topográficas',
  'cartas orto': 'Cartas Ortoimagem',
  'cartas ortoimg': 'Cartas Ortoimagem',

  // Abreviações de estados
  rj: 'Rio de Janeiro',
  sp: 'São Paulo',
  mg: 'Minas Gerais',
  es: 'Espírito Santo',
  pr: 'Paraná',
  sc: 'Santa Catarina',
  rs: 'Rio Grande do Sul',
  ms: 'Mato Grosso do Sul',
  mt: 'Mato Grosso',
  go: 'Goiás',
  df: 'Distrito Federal',
  ba: 'Bahia',
  se: 'Sergipe',
  al: 'Alagoas',
  pe: 'Pernambuco',
  pb: 'Paraíba',
  rn: 'Rio Grande do Norte',
  ce: 'Ceará',
  pi: 'Piauí',
  ma: 'Maranhão',
  pa: 'Pará',
  ap: 'Amapá',
  am: 'Amazonas',
  rr: 'Roraima',
  ac: 'Acre',
  ro: 'Rondônia',
  to: 'Tocantins',

  // Termos comuns de ordenação
  'mais novo': 'mais recente',
  'mais nova': 'mais recente',
  'mais novos': 'mais recente',
  'mais novas': 'mais recente',
  'mais antigo': 'mais antiga',
  'mais antiga': 'mais antiga',
  'mais antigos': 'mais antiga',
  'mais antigas': 'mais antiga',
  'ordem crescente': 'mais antiga',
  'ordem decrescente': 'mais recente',

  // Projetos
  copa: 'Copa do Mundo 2014',
  'copa 2014': 'Copa do Mundo 2014',
  olimpiada: 'Olimpíadas',
  olimpiadas: 'Olimpíadas',
  olimpíada: 'Olimpíadas',
};
