export const COMMON_TERMS: Record<string, string> = {
  // Siglas e Variações de Centros de Geoinformação
  // Combinações com números
  '1cgeo': '1° Centro de Geoinformação',
  '2cgeo': '2° Centro de Geoinformação',
  '3cgeo': '3° Centro de Geoinformação',
  '4cgeo': '4° Centro de Geoinformação',
  '5cgeo': '5° Centro de Geoinformação',
  // Combinações com espaço
  '1 cgeo': '1° Centro de Geoinformação',
  '2 cgeo': '2° Centro de Geoinformação',
  '3 cgeo': '3° Centro de Geoinformação',
  '4 cgeo': '4° Centro de Geoinformação',
  '5 cgeo': '5° Centro de Geoinformação',
  // Variações com º
  '1ºcgeo': '1° Centro de Geoinformação',
  '2ºcgeo': '2° Centro de Geoinformação',
  '3ºcgeo': '3° Centro de Geoinformação',
  '4ºcgeo': '4° Centro de Geoinformação',
  '5ºcgeo': '5° Centro de Geoinformação',
  // Variações com º e espaço
  '1º cgeo': '1° Centro de Geoinformação',
  '2º cgeo': '2° Centro de Geoinformação',
  '3º cgeo': '3° Centro de Geoinformação',
  '4º cgeo': '4° Centro de Geoinformação',
  '5º cgeo': '5° Centro de Geoinformação',
  // Variações com o
  '1ocgeo': '1° Centro de Geoinformação',
  '2ocgeo': '2° Centro de Geoinformação',
  '3ocgeo': '3° Centro de Geoinformação',
  '4ocgeo': '4° Centro de Geoinformação',
  '5ocgeo': '5° Centro de Geoinformação',
  // Variações com o e espaço
  '1o cgeo': '1° Centro de Geoinformação',
  '2o cgeo': '2° Centro de Geoinformação',
  '3o cgeo': '3° Centro de Geoinformação',
  '4o cgeo': '4° Centro de Geoinformação',
  '5o cgeo': '5° Centro de Geoinformação',
  // Variações por extenso
  'primeiro cgeo': '1° Centro de Geoinformação',
  'segundo cgeo': '2° Centro de Geoinformação',
  'terceiro cgeo': '3° Centro de Geoinformação',
  'quarto cgeo': '4° Centro de Geoinformação',
  'quinto cgeo': '5° Centro de Geoinformação',
  'primeiro centro': '1° Centro de Geoinformação',
  'segundo centro': '2° Centro de Geoinformação',
  'terceiro centro': '3° Centro de Geoinformação',
  'quarto centro': '4° Centro de Geoinformação',
  'quinto centro': '5° Centro de Geoinformação',

  // Abreviações de escalas com variações
  '25k': '1:25.000',
  '25.k': '1:25.000',
  '25 k': '1:25.000',
  '25.000': '1:25.000',
  '25000': '1:25.000',
  '50k': '1:50.000',
  '50.k': '1:50.000',
  '50 k': '1:50.000',
  '50.000': '1:50.000',
  '50000': '1:50.000',
  '100k': '1:100.000',
  '100.k': '1:100.000',
  '100 k': '1:100.000',
  '100.000': '1:100.000',
  '100000': '1:100.000',
  '250k': '1:250.000',
  '250.k': '1:250.000',
  '250 k': '1:250.000',
  '250.000': '1:250.000',
  '250000': '1:250.000',
  // Descrições de escala
  'grande escala': '1:25.000',
  'maior escala': '1:25.000',
  'escala grande': '1:25.000',
  'escala maior': '1:25.000',
  'media escala': '1:100.000',
  'média escala': '1:100.000',
  'escala media': '1:100.000',
  'escala média': '1:100.000',
  'pequena escala': '1:250.000',
  'menor escala': '1:250.000',
  'escala pequena': '1:250.000',
  'escala menor': '1:250.000',

  // Abreviações de tipos de produto
  'carta topo': 'Carta Topográfica',
  'cartas topo': 'Carta Topográfica',
  'carta topografica': 'Carta Topográfica',
  'carta orto': 'Carta Ortoimagem',
  'cartas orto': 'Carta Ortoimagem',
  'carta ortoimg': 'Carta Ortoimagem',
  'cartas ortoimg': 'Carta Ortoimagem',
  'carta tematica': 'Carta Temática',
  'carta temática': 'Carta Temática',
  'cartas tematicas': 'Carta Temática',
  'cartas temáticas': 'Carta Temática',
  'imagem satelite': 'Carta Ortoimagem',
  'imagem de satelite': 'Carta Ortoimagem',
  'imagem por satelite': 'Carta Ortoimagem',

  // Abreviações de estados (mantido apenas os mais comuns para evitar falsos positivos)
  'rj': 'Rio de Janeiro',
  'sp': 'São Paulo',
  'mg': 'Minas Gerais',
  'es': 'Espírito Santo',
  'pr': 'Paraná',
  'sc': 'Santa Catarina',
  'rs': 'Rio Grande do Sul',
  'df': 'Distrito Federal',
  'ba': 'Bahia',
  'am': 'Amazonas',
  'pa': 'Pará',
  'ap': 'Amapá',
  'ro': 'Rondônia',

  // Projetos e variações
  'copa 2014': 'Copa do Mundo 2014',
  'olimpiada': 'Olimpíadas',
  'olimpiadas': 'Olimpíadas',
  'olimpíada': 'Olimpíadas',
  'jogos olimpicos': 'Olimpíadas',
  'jogos olímpicos': 'Olimpíadas'
};